name: Create release

on:
    workflow_dispatch:
    push:
        tags:
            - "v*.*.*"

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
                  fetch-depth: 0

            - name: Check Nixpkgs inputs
              uses: DeterminateSystems/flake-checker-action@main
              with:
                  fail-mode: true

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main

            - name: Prettier
              run: |
                  nix develop --command \
                      just check-prettier

            - name: CMake-format
              run: |
                  nix develop --command \
                      just check-cmakeformat

            - name: C-format
              run: |
                  nix develop --command \
                      just check-uncrustify

            - name: Build
              run: |
                  nix develop --command \
                      just build_all

            - name: Test
              run: |
                  nix develop --command \
                    just test_all

            - name: html
              run: |
                  nix develop --command \
                    just html 
            
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: ./docs/.build/html

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
